export const SET_DATA = 'SET_DATA'
export const SET_DATA_FAILED = 'SET_DATA_FAILED'
export const SET_DATA_FROM_API = 'SET_DATA_FROM_API'
export const SET_DATA_ACCOUNTS = 'SET_DATA_ACCOUNTS'
export const SET_DATA_ROOMS = 'SET_DATA_ROOMS'


export const SET_USERS_FAILED = 'SET_USERS_FAILED'
export const SET_QUESTIONS_FAILED = 'SET_QUESTIONS_FAILED'
export const SET_IS_USER_READY_TO_QUIZ = 'SET_IS_USER_READY_TO_QUIZ'
export const UNSET_IS_USER_READY_TO_QUIZ = 'UNSET_IS_USER_READY_TO_QUIZ'
export const SET_IS_USER_READY_TO_QUIZ_FAILED = 'SET_IS_USER_READY_TO_QUIZ_FAILED'
export const UNSET_IS_USER_READY_TO_QUIZ_FAILED = 'UNSET_IS_USER_READY_TO_QUIZ_FAILED'
export const SET_QUIZ = 'SET_QUIZ'
export const SET_QUIZ_WAITING = 'SET_QUIZ_WAITING'
export const SET_ANSWER = 'SET_ANSWER'
export const UNSET_ANSWER = 'UNSET_ANSWER'
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'
export const SET_QUIZ_RESULTS = 'SET_QUIZ_RESULTS'
export const SET_QUIZ_RESULTS_FAILED = 'SET_QUIZ_RESULTS_FAILED'
export const SET_USERS_RESULTS_LIST = 'SET_USERS_RESULTS_LIST'
export const SET_CORRECT_ANSWER_COUNT = 'SET_CORRECT_ANSWER_COUNT'
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE'
export const SEND = 'SEND'
export const SET_USER_MESSAGE = 'SET_USER_MESSAGE'
export const SET_USER_MESSAGE_FAILED = 'SET_USER_MESSAGE_FAILED'
export const SET_USER_RESULTS = 'SET_USER_RESULTS'
export const SET_LAST_MESSAGE = 'SET_LAST_MESSAGE'
export const SET_USER_MESSAGES = 'SET_USER_MESSAGES'
export const SEND_MESSAGES_TO_STORE = 'SEND_MESSAGES_TO_STORE'







